pipeline:
  name: Test
  identifier: Test
  projectIdentifier: Firstproject
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: thomaspradeep/python-pipelines-samples
        build: <+input>
  stages:
    - stage:
        name: First
        identifier: First
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: pwd
        delegateSelectors:
          - docker-delegate
